version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lulateko
      RABBITMQ_DEFAULT_PASS: lulateko
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  stock-publisher:
    image: lstockerteko/stock-publisher:latest
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
    depends_on:
      - rabbitmq
    restart: on-failure

  consumer-msft:
    build:
      context: ./consumer
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
      RABBITMQ_QUEUE: MSFT
      MONGODB_URI: mongodb://mongo0:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      - rabbitmq
      - mongo0
    restart: on-failure

  consumer-tsla:
    build:
      context: ./consumer
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
      RABBITMQ_QUEUE: TSLA
      MONGODB_URI: mongodb://mongo0:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      - rabbitmq
      - mongo0
    restart: on-failure

  consumer-aapl:
    build:
      context: ./consumer
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
      RABBITMQ_QUEUE: AAPL
      MONGODB_URI: mongodb://mongo0:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      - rabbitmq
      - mongo0
    restart: on-failure
    
  mongo0:
    image: mongo:7.0
    container_name: mongo0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data0:/data/db
      - mongo_config0:/data/configdb

  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - "27018:27017"
    volumes:
      - mongo_data1:/data/db
      - mongo_config1:/data/configdb

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - "27019:27017"
    volumes:
      - mongo_data2:/data/db
      - mongo_config2:/data/configdb

  stock-liveview:
    image: lucamteko/stock-liveview:latest
    container_name: stock-liveview
    environment:
      MONGODB_URI: mongodb://mongo0:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks    
    ports:
      - "3000:3000"
    depends_on:
      - mongo0
    restart: on-failure

volumes:
  rabbitmq_data:
  mongo_data0:
  mongo_config0:
  mongo_data1:
  mongo_config1:
  mongo_data2:
  mongo_config2:
