version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lulateko
      RABBITMQ_DEFAULT_PASS: lulateko
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  stock-publisher:
    image: lstockerteko/stock-publisher:latest
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
    depends_on:
      - rabbitmq
    restart: on-failure

  consumer-msft:
    build:
      context: ./consumer
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
      RABBITMQ_QUEUE: MSFT
      MONGODB_URI: mongodb://mongo:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure

  consumer-tsla:
    build:
      context: ./consumer
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
      RABBITMQ_QUEUE: TSLA
      MONGODB_URI: mongodb://mongo:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure

  consumer-aapl:
    build:
      context: ./consumer
    environment:
      RABBITMQ_URL: amqp://lulateko:lulateko@rabbitmq:5672/
      RABBITMQ_QUEUE: AAPL
      MONGODB_URI: mongodb://mongo:27017/
      MONGODB_DB: stockmarket
      MONGODB_COLLECTION: stocks
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
    
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  rabbitmq_data:
  mongo_data:
