version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lulateko
      RABBITMQ_DEFAULT_PASS: lulatekopass
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: on-failure

  stock-publisher:
    image: lucamteko/stock-publisher:latest
    container_name: stock-publisher
    environment:
      RABBITMQ_URL: amqp://lulateko:lulatekopass@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  consumer-msft:
    image: lucamteko/consumer:latest
    container_name: consumer-msft
    environment:
      RABBITMQ_QUEUE: MSFT
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo0:
        condition: service_healthy
    restart: on-failure

  consumer-tsla:
    image: lucamteko/consumer:latest
    container_name: consumer-tsla
    environment:
      RABBITMQ_QUEUE: TSLA
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo0:
        condition: service_healthy
    restart: on-failure

  consumer-aapl:
    image: lucamteko/consumer:latest
    container_name: consumer-aapl
    environment:
      RABBITMQ_QUEUE: AAPL
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo0:
        condition: service_healthy
    restart: on-failure
    
  mongo0:
    image: mongo:7.0
    container_name: mongo0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data0:/data/db
      - mongo_config0:/data/configdb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet 
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    restart: on-failure

  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - "27018:27018"
    volumes:
      - mongo_data1:/data/db
      - mongo_config1:/data/configdb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - "27019:27019"
    volumes:
      - mongo_data2:/data/db
      - mongo_config2:/data/configdb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  stock-liveview0:
    image: lucamteko/stock-liveview:latest
    container_name: stock-liveview0
    ports:
      - "3000:3000"
    depends_on:
      mongo0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure

  stock-liveview1:
    image: lucamteko/stock-liveview:latest
    container_name: stock-liveview1
    ports:
      - "3001:3000"
    depends_on:
      mongo0:
        condition: service_healthy
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      stock-liveview0:
        condition: service_healthy
    restart: always

volumes:
  mongo_data0:
  mongo_config0:
  mongo_data1:
  mongo_config1:
  mongo_data2:
  mongo_config2:
