version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Port für die Kommunikation mit RabbitMQ
      - "15672:15672"  # Port für das Management-UI
    environment:
      RABBITMQ_DEFAULT_USER: lulateko
      RABBITMQ_DEFAULT_PASS: lulateko
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
